(defun my-remove-duplicates (str)
  (let ((input-list (coerce str 'list))
        (result '())
        (seen '()))
    (dolist (char input-list)
      (when (not (member char seen))
        (push char result)
        (push char seen)))
    (reverse (coerce result 'string))))
